### ISSUE TITLE
Optimize configuration

### ISSUE THREAD

**Issue by hagenburger** [hagenburger/livingstyleguide#77]
Just a work in progress to optimize the configuration:

Proposal: 

``` yaml
# CSS
css:
  # Your main Sass file (used to be `source:`):
  - my-styles.css.scss

# ------------------------- EVERYTHING BELOW IS OPTIONAL ------------------------- #

  # Possible other Sass file (e.g. you split up your production CSS):
  - my-other-styles.css.scss
  # E.g. custom styles for the style guide itself (would import _styleguide.scss):
  - styleguide
  # Include this file via `@import "css-file.css"`:
  - css-file.css

  # It’s also possible to include CSS/SCSS/Sass here, 
  # but maybe messes up the file a bit (including an 
  # external file (see above) might be better for you):
  - '.my-element { color: red }'  
  # For long/multi-line Sass/SCSS code YAML also supports the pipe syntax:
  - |
    .some {
      multi: line;
      sass: code;
    }

# Default settings for calculating the style guide design:
style:
  base-font: 'Helvetica Neue, Helvetica, Arial, sans-serif'
  color: '$my-color'
  code-color: 'adjust-hue($base-color, 180deg)'

# Additional JavaScript includes:
javascript:
  before:
    - /javascripts/modernizr.js
  after:
    - http://code.jquery.com/jquery-2.1.0.min.js
    - /javascripts/underscore-1.6.0.min.js
    - /javascripts/my-application.js
    - 'alert("Hello World!")'

# Import another YAML file with defaults (when you have multiple 
# style guides, e.g. for customer brandig):
defaults:
  - defaults.lsg
# I do not like the name `defaults` yet. It should be clear those files 
# are loaded and overridden by the settings in this file.
```

Current:

``` yaml
source: my-styles.css.scss

# ------------------------- EVERYTHING BELOW IS OPTIONAL ------------------------- #

style:
  base-font: 'Helvetica Neue, Helvetica, Arial, sans-serif'
  color: '$my-color'
  code-color: 'adjust-hue($base-color, 180deg)'

styleguide-scss: |
  .some-custom {
    css: for;
    displaying-your: styleguide;
  }

javascript-before:
  - /javascripts/modernizr.js

javascript-after:
  - http://code.jquery.com/jquery-2.1.0.min.js
  - /javascripts/underscore-1.6.0.min.js
  - /javascripts/my-application.js
```
